name: Build Documentation
on:
  push:
    branches:
    - gh-pages
jobs:
  tacobot:
    runs-on: ubuntu-18.04
    name: Build TacoBot Documentation
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: 'TacoContent/TacoBot'
        path: 'generate/tacobotdiscord/'
        ref: 'develop'
    - uses: actions/checkout@v3
      with:
        repository: 'TacoContent/tacobottwitch'
        path: 'generate/tacobottwitch/'
        ref: 'develop'

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: run generate discord documentation
      run: |
        python generate_discord.py > discord.md
    - name: run generate twitch documentation
      run: |
        python generate_twitch.py > twitch.md

    - uses: EndBug/add-and-commit@v9
      with:
        message: 'Documentation Generated'
