name: Build Documentation
on:
  push:
    branches:
    - gh-pages
  schedule:
  - cron: '0 12 * * *'
  repository_dispatch:
    types:
    - build_documentation
jobs:
  generate_documentation:
    runs-on: ubuntu-latest
    name: Build TacoBot Documentation
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: 'TacoContent/TacoBot'
        path: 'generate/tacobotdiscord/'
        ref: 'develop'
    - uses: actions/checkout@v3
      with:
        repository: 'TacoContent/tacobottwitch'
        path: 'generate/tacobottwitch/'
        ref: 'develop'
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: run generate discord documentation
      run: |
        python generate_discord.py > discord.md
    - name: run generate twitch documentation
      run: |
        python generate_twitch.py > twitch.md

    - uses: EndBug/add-and-commit@v9
      with:
        message: 'Documentation Generated'
