name: Build Documentation
on:
  push:
    branches:
    - gh-pages
jobs:
  tacobot:
    runs-on: ubuntu-18.04
    name: Build TacoBot Documentation
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'TacoContent/TacoBot'
        token: "${{ github.token }}"
        path: 'generate/tacobot/'
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: run generate documentation
      run: |
        python generate_twitch.py > twitch-test.md

  commit:
    runs-on: ubuntu-18.04
    name: commit changes
    steps:
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'Documentation Generated'
